// Code generated by ent, DO NOT EDIT.

package risksessionblacklist

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the risksessionblacklist type in the database.
	Label = "risk_session_blacklist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSessionHash holds the string denoting the session_hash field in the database.
	FieldSessionHash = "session_hash"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldCategories holds the string denoting the categories field in the database.
	FieldCategories = "categories"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldAuditModel holds the string denoting the audit_model field in the database.
	FieldAuditModel = "audit_model"
	// FieldAuditResponseID holds the string denoting the audit_response_id field in the database.
	FieldAuditResponseID = "audit_response_id"
	// FieldSourceProtocol holds the string denoting the source_protocol field in the database.
	FieldSourceProtocol = "source_protocol"
	// FieldSourceModel holds the string denoting the source_model field in the database.
	FieldSourceModel = "source_model"
	// FieldFirstBlockedAt holds the string denoting the first_blocked_at field in the database.
	FieldFirstBlockedAt = "first_blocked_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the risksessionblacklist in the database.
	Table = "risk_session_blacklists"
)

// Columns holds all SQL columns for risksessionblacklist fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSessionHash,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldReason,
	FieldCategories,
	FieldConfidence,
	FieldAuditModel,
	FieldAuditResponseID,
	FieldSourceProtocol,
	FieldSourceModel,
	FieldFirstBlockedAt,
	FieldLastSeenAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SessionHashValidator is a validator for the "session_hash" field. It is called by the builders before save.
	SessionHashValidator func(string) error
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
	// DefaultConfidence holds the default value on creation for the "confidence" field.
	DefaultConfidence float64
	// DefaultAuditModel holds the default value on creation for the "audit_model" field.
	DefaultAuditModel string
	// DefaultAuditResponseID holds the default value on creation for the "audit_response_id" field.
	DefaultAuditResponseID string
	// DefaultSourceProtocol holds the default value on creation for the "source_protocol" field.
	DefaultSourceProtocol string
	// DefaultSourceModel holds the default value on creation for the "source_model" field.
	DefaultSourceModel string
)

// OrderOption defines the ordering options for the RiskSessionBlacklist queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySessionHash orders the results by the session_hash field.
func BySessionHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionHash, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByAuditModel orders the results by the audit_model field.
func ByAuditModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditModel, opts...).ToFunc()
}

// ByAuditResponseID orders the results by the audit_response_id field.
func ByAuditResponseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditResponseID, opts...).ToFunc()
}

// BySourceProtocol orders the results by the source_protocol field.
func BySourceProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceProtocol, opts...).ToFunc()
}

// BySourceModel orders the results by the source_model field.
func BySourceModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceModel, opts...).ToFunc()
}

// ByFirstBlockedAt orders the results by the first_blocked_at field.
func ByFirstBlockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstBlockedAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
