// Code generated by ent, DO NOT EDIT.

package risksessionblacklist

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionHash applies equality check predicate on the "session_hash" field. It's identical to SessionHashEQ.
func SessionHash(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldSessionHash, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldGroupID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldReason, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldConfidence, v))
}

// AuditModel applies equality check predicate on the "audit_model" field. It's identical to AuditModelEQ.
func AuditModel(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldAuditModel, v))
}

// AuditResponseID applies equality check predicate on the "audit_response_id" field. It's identical to AuditResponseIDEQ.
func AuditResponseID(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldAuditResponseID, v))
}

// SourceProtocol applies equality check predicate on the "source_protocol" field. It's identical to SourceProtocolEQ.
func SourceProtocol(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldSourceProtocol, v))
}

// SourceModel applies equality check predicate on the "source_model" field. It's identical to SourceModelEQ.
func SourceModel(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldSourceModel, v))
}

// FirstBlockedAt applies equality check predicate on the "first_blocked_at" field. It's identical to FirstBlockedAtEQ.
func FirstBlockedAt(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldFirstBlockedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldLastSeenAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldUpdatedAt, v))
}

// SessionHashEQ applies the EQ predicate on the "session_hash" field.
func SessionHashEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldSessionHash, v))
}

// SessionHashNEQ applies the NEQ predicate on the "session_hash" field.
func SessionHashNEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldSessionHash, v))
}

// SessionHashIn applies the In predicate on the "session_hash" field.
func SessionHashIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldSessionHash, vs...))
}

// SessionHashNotIn applies the NotIn predicate on the "session_hash" field.
func SessionHashNotIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldSessionHash, vs...))
}

// SessionHashGT applies the GT predicate on the "session_hash" field.
func SessionHashGT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldSessionHash, v))
}

// SessionHashGTE applies the GTE predicate on the "session_hash" field.
func SessionHashGTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldSessionHash, v))
}

// SessionHashLT applies the LT predicate on the "session_hash" field.
func SessionHashLT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldSessionHash, v))
}

// SessionHashLTE applies the LTE predicate on the "session_hash" field.
func SessionHashLTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldSessionHash, v))
}

// SessionHashContains applies the Contains predicate on the "session_hash" field.
func SessionHashContains(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContains(FieldSessionHash, v))
}

// SessionHashHasPrefix applies the HasPrefix predicate on the "session_hash" field.
func SessionHashHasPrefix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasPrefix(FieldSessionHash, v))
}

// SessionHashHasSuffix applies the HasSuffix predicate on the "session_hash" field.
func SessionHashHasSuffix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasSuffix(FieldSessionHash, v))
}

// SessionHashEqualFold applies the EqualFold predicate on the "session_hash" field.
func SessionHashEqualFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEqualFold(FieldSessionHash, v))
}

// SessionHashContainsFold applies the ContainsFold predicate on the "session_hash" field.
func SessionHashContainsFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContainsFold(FieldSessionHash, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotNull(FieldUserID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotNull(FieldAPIKeyID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotNull(FieldGroupID))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContainsFold(FieldReason, v))
}

// CategoriesIsNil applies the IsNil predicate on the "categories" field.
func CategoriesIsNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIsNull(FieldCategories))
}

// CategoriesNotNil applies the NotNil predicate on the "categories" field.
func CategoriesNotNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotNull(FieldCategories))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldConfidence, v))
}

// AuditModelEQ applies the EQ predicate on the "audit_model" field.
func AuditModelEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldAuditModel, v))
}

// AuditModelNEQ applies the NEQ predicate on the "audit_model" field.
func AuditModelNEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldAuditModel, v))
}

// AuditModelIn applies the In predicate on the "audit_model" field.
func AuditModelIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldAuditModel, vs...))
}

// AuditModelNotIn applies the NotIn predicate on the "audit_model" field.
func AuditModelNotIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldAuditModel, vs...))
}

// AuditModelGT applies the GT predicate on the "audit_model" field.
func AuditModelGT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldAuditModel, v))
}

// AuditModelGTE applies the GTE predicate on the "audit_model" field.
func AuditModelGTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldAuditModel, v))
}

// AuditModelLT applies the LT predicate on the "audit_model" field.
func AuditModelLT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldAuditModel, v))
}

// AuditModelLTE applies the LTE predicate on the "audit_model" field.
func AuditModelLTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldAuditModel, v))
}

// AuditModelContains applies the Contains predicate on the "audit_model" field.
func AuditModelContains(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContains(FieldAuditModel, v))
}

// AuditModelHasPrefix applies the HasPrefix predicate on the "audit_model" field.
func AuditModelHasPrefix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasPrefix(FieldAuditModel, v))
}

// AuditModelHasSuffix applies the HasSuffix predicate on the "audit_model" field.
func AuditModelHasSuffix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasSuffix(FieldAuditModel, v))
}

// AuditModelEqualFold applies the EqualFold predicate on the "audit_model" field.
func AuditModelEqualFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEqualFold(FieldAuditModel, v))
}

// AuditModelContainsFold applies the ContainsFold predicate on the "audit_model" field.
func AuditModelContainsFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContainsFold(FieldAuditModel, v))
}

// AuditResponseIDEQ applies the EQ predicate on the "audit_response_id" field.
func AuditResponseIDEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldAuditResponseID, v))
}

// AuditResponseIDNEQ applies the NEQ predicate on the "audit_response_id" field.
func AuditResponseIDNEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldAuditResponseID, v))
}

// AuditResponseIDIn applies the In predicate on the "audit_response_id" field.
func AuditResponseIDIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldAuditResponseID, vs...))
}

// AuditResponseIDNotIn applies the NotIn predicate on the "audit_response_id" field.
func AuditResponseIDNotIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldAuditResponseID, vs...))
}

// AuditResponseIDGT applies the GT predicate on the "audit_response_id" field.
func AuditResponseIDGT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldAuditResponseID, v))
}

// AuditResponseIDGTE applies the GTE predicate on the "audit_response_id" field.
func AuditResponseIDGTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldAuditResponseID, v))
}

// AuditResponseIDLT applies the LT predicate on the "audit_response_id" field.
func AuditResponseIDLT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldAuditResponseID, v))
}

// AuditResponseIDLTE applies the LTE predicate on the "audit_response_id" field.
func AuditResponseIDLTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldAuditResponseID, v))
}

// AuditResponseIDContains applies the Contains predicate on the "audit_response_id" field.
func AuditResponseIDContains(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContains(FieldAuditResponseID, v))
}

// AuditResponseIDHasPrefix applies the HasPrefix predicate on the "audit_response_id" field.
func AuditResponseIDHasPrefix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasPrefix(FieldAuditResponseID, v))
}

// AuditResponseIDHasSuffix applies the HasSuffix predicate on the "audit_response_id" field.
func AuditResponseIDHasSuffix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasSuffix(FieldAuditResponseID, v))
}

// AuditResponseIDEqualFold applies the EqualFold predicate on the "audit_response_id" field.
func AuditResponseIDEqualFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEqualFold(FieldAuditResponseID, v))
}

// AuditResponseIDContainsFold applies the ContainsFold predicate on the "audit_response_id" field.
func AuditResponseIDContainsFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContainsFold(FieldAuditResponseID, v))
}

// SourceProtocolEQ applies the EQ predicate on the "source_protocol" field.
func SourceProtocolEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldSourceProtocol, v))
}

// SourceProtocolNEQ applies the NEQ predicate on the "source_protocol" field.
func SourceProtocolNEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldSourceProtocol, v))
}

// SourceProtocolIn applies the In predicate on the "source_protocol" field.
func SourceProtocolIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldSourceProtocol, vs...))
}

// SourceProtocolNotIn applies the NotIn predicate on the "source_protocol" field.
func SourceProtocolNotIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldSourceProtocol, vs...))
}

// SourceProtocolGT applies the GT predicate on the "source_protocol" field.
func SourceProtocolGT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldSourceProtocol, v))
}

// SourceProtocolGTE applies the GTE predicate on the "source_protocol" field.
func SourceProtocolGTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldSourceProtocol, v))
}

// SourceProtocolLT applies the LT predicate on the "source_protocol" field.
func SourceProtocolLT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldSourceProtocol, v))
}

// SourceProtocolLTE applies the LTE predicate on the "source_protocol" field.
func SourceProtocolLTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldSourceProtocol, v))
}

// SourceProtocolContains applies the Contains predicate on the "source_protocol" field.
func SourceProtocolContains(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContains(FieldSourceProtocol, v))
}

// SourceProtocolHasPrefix applies the HasPrefix predicate on the "source_protocol" field.
func SourceProtocolHasPrefix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasPrefix(FieldSourceProtocol, v))
}

// SourceProtocolHasSuffix applies the HasSuffix predicate on the "source_protocol" field.
func SourceProtocolHasSuffix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasSuffix(FieldSourceProtocol, v))
}

// SourceProtocolEqualFold applies the EqualFold predicate on the "source_protocol" field.
func SourceProtocolEqualFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEqualFold(FieldSourceProtocol, v))
}

// SourceProtocolContainsFold applies the ContainsFold predicate on the "source_protocol" field.
func SourceProtocolContainsFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContainsFold(FieldSourceProtocol, v))
}

// SourceModelEQ applies the EQ predicate on the "source_model" field.
func SourceModelEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldSourceModel, v))
}

// SourceModelNEQ applies the NEQ predicate on the "source_model" field.
func SourceModelNEQ(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldSourceModel, v))
}

// SourceModelIn applies the In predicate on the "source_model" field.
func SourceModelIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldSourceModel, vs...))
}

// SourceModelNotIn applies the NotIn predicate on the "source_model" field.
func SourceModelNotIn(vs ...string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldSourceModel, vs...))
}

// SourceModelGT applies the GT predicate on the "source_model" field.
func SourceModelGT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldSourceModel, v))
}

// SourceModelGTE applies the GTE predicate on the "source_model" field.
func SourceModelGTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldSourceModel, v))
}

// SourceModelLT applies the LT predicate on the "source_model" field.
func SourceModelLT(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldSourceModel, v))
}

// SourceModelLTE applies the LTE predicate on the "source_model" field.
func SourceModelLTE(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldSourceModel, v))
}

// SourceModelContains applies the Contains predicate on the "source_model" field.
func SourceModelContains(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContains(FieldSourceModel, v))
}

// SourceModelHasPrefix applies the HasPrefix predicate on the "source_model" field.
func SourceModelHasPrefix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasPrefix(FieldSourceModel, v))
}

// SourceModelHasSuffix applies the HasSuffix predicate on the "source_model" field.
func SourceModelHasSuffix(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldHasSuffix(FieldSourceModel, v))
}

// SourceModelEqualFold applies the EqualFold predicate on the "source_model" field.
func SourceModelEqualFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEqualFold(FieldSourceModel, v))
}

// SourceModelContainsFold applies the ContainsFold predicate on the "source_model" field.
func SourceModelContainsFold(v string) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldContainsFold(FieldSourceModel, v))
}

// FirstBlockedAtEQ applies the EQ predicate on the "first_blocked_at" field.
func FirstBlockedAtEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldFirstBlockedAt, v))
}

// FirstBlockedAtNEQ applies the NEQ predicate on the "first_blocked_at" field.
func FirstBlockedAtNEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldFirstBlockedAt, v))
}

// FirstBlockedAtIn applies the In predicate on the "first_blocked_at" field.
func FirstBlockedAtIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldFirstBlockedAt, vs...))
}

// FirstBlockedAtNotIn applies the NotIn predicate on the "first_blocked_at" field.
func FirstBlockedAtNotIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldFirstBlockedAt, vs...))
}

// FirstBlockedAtGT applies the GT predicate on the "first_blocked_at" field.
func FirstBlockedAtGT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldFirstBlockedAt, v))
}

// FirstBlockedAtGTE applies the GTE predicate on the "first_blocked_at" field.
func FirstBlockedAtGTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldFirstBlockedAt, v))
}

// FirstBlockedAtLT applies the LT predicate on the "first_blocked_at" field.
func FirstBlockedAtLT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldFirstBlockedAt, v))
}

// FirstBlockedAtLTE applies the LTE predicate on the "first_blocked_at" field.
func FirstBlockedAtLTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldFirstBlockedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldLastSeenAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RiskSessionBlacklist) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RiskSessionBlacklist) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RiskSessionBlacklist) predicate.RiskSessionBlacklist {
	return predicate.RiskSessionBlacklist(sql.NotPredicates(p))
}
