// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/risksessionblacklist"
)

// RiskSessionBlacklist is the model entity for the RiskSessionBlacklist schema.
type RiskSessionBlacklist struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SessionHash holds the value of the "session_hash" field.
	SessionHash string `json:"session_hash,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Categories holds the value of the "categories" field.
	Categories []string `json:"categories,omitempty"`
	// Confidence holds the value of the "confidence" field.
	Confidence float64 `json:"confidence,omitempty"`
	// AuditModel holds the value of the "audit_model" field.
	AuditModel string `json:"audit_model,omitempty"`
	// AuditResponseID holds the value of the "audit_response_id" field.
	AuditResponseID string `json:"audit_response_id,omitempty"`
	// SourceProtocol holds the value of the "source_protocol" field.
	SourceProtocol string `json:"source_protocol,omitempty"`
	// SourceModel holds the value of the "source_model" field.
	SourceModel string `json:"source_model,omitempty"`
	// FirstBlockedAt holds the value of the "first_blocked_at" field.
	FirstBlockedAt time.Time `json:"first_blocked_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RiskSessionBlacklist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case risksessionblacklist.FieldCategories:
			values[i] = new([]byte)
		case risksessionblacklist.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case risksessionblacklist.FieldID, risksessionblacklist.FieldUserID, risksessionblacklist.FieldAPIKeyID, risksessionblacklist.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case risksessionblacklist.FieldSessionHash, risksessionblacklist.FieldReason, risksessionblacklist.FieldAuditModel, risksessionblacklist.FieldAuditResponseID, risksessionblacklist.FieldSourceProtocol, risksessionblacklist.FieldSourceModel:
			values[i] = new(sql.NullString)
		case risksessionblacklist.FieldCreatedAt, risksessionblacklist.FieldUpdatedAt, risksessionblacklist.FieldFirstBlockedAt, risksessionblacklist.FieldLastSeenAt, risksessionblacklist.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RiskSessionBlacklist fields.
func (_m *RiskSessionBlacklist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case risksessionblacklist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case risksessionblacklist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case risksessionblacklist.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case risksessionblacklist.FieldSessionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_hash", values[i])
			} else if value.Valid {
				_m.SessionHash = value.String
			}
		case risksessionblacklist.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case risksessionblacklist.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case risksessionblacklist.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case risksessionblacklist.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case risksessionblacklist.FieldCategories:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field categories", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Categories); err != nil {
					return fmt.Errorf("unmarshal field categories: %w", err)
				}
			}
		case risksessionblacklist.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case risksessionblacklist.FieldAuditModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audit_model", values[i])
			} else if value.Valid {
				_m.AuditModel = value.String
			}
		case risksessionblacklist.FieldAuditResponseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audit_response_id", values[i])
			} else if value.Valid {
				_m.AuditResponseID = value.String
			}
		case risksessionblacklist.FieldSourceProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_protocol", values[i])
			} else if value.Valid {
				_m.SourceProtocol = value.String
			}
		case risksessionblacklist.FieldSourceModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_model", values[i])
			} else if value.Valid {
				_m.SourceModel = value.String
			}
		case risksessionblacklist.FieldFirstBlockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_blocked_at", values[i])
			} else if value.Valid {
				_m.FirstBlockedAt = value.Time
			}
		case risksessionblacklist.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case risksessionblacklist.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RiskSessionBlacklist.
// This includes values selected through modifiers, order, etc.
func (_m *RiskSessionBlacklist) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RiskSessionBlacklist.
// Note that you need to call RiskSessionBlacklist.Unwrap() before calling this method if this RiskSessionBlacklist
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RiskSessionBlacklist) Update() *RiskSessionBlacklistUpdateOne {
	return NewRiskSessionBlacklistClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RiskSessionBlacklist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RiskSessionBlacklist) Unwrap() *RiskSessionBlacklist {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RiskSessionBlacklist is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RiskSessionBlacklist) String() string {
	var builder strings.Builder
	builder.WriteString("RiskSessionBlacklist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_hash=")
	builder.WriteString(_m.SessionHash)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("categories=")
	builder.WriteString(fmt.Sprintf("%v", _m.Categories))
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("audit_model=")
	builder.WriteString(_m.AuditModel)
	builder.WriteString(", ")
	builder.WriteString("audit_response_id=")
	builder.WriteString(_m.AuditResponseID)
	builder.WriteString(", ")
	builder.WriteString("source_protocol=")
	builder.WriteString(_m.SourceProtocol)
	builder.WriteString(", ")
	builder.WriteString("source_model=")
	builder.WriteString(_m.SourceModel)
	builder.WriteString(", ")
	builder.WriteString("first_blocked_at=")
	builder.WriteString(_m.FirstBlockedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RiskSessionBlacklists is a parsable slice of RiskSessionBlacklist.
type RiskSessionBlacklists []*RiskSessionBlacklist
