// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/risksessionblacklist"
)

// RiskSessionBlacklistCreate is the builder for creating a RiskSessionBlacklist entity.
type RiskSessionBlacklistCreate struct {
	config
	mutation *RiskSessionBlacklistMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RiskSessionBlacklistCreate) SetCreatedAt(v time.Time) *RiskSessionBlacklistCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableCreatedAt(v *time.Time) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RiskSessionBlacklistCreate) SetUpdatedAt(v time.Time) *RiskSessionBlacklistCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableUpdatedAt(v *time.Time) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSessionHash sets the "session_hash" field.
func (_c *RiskSessionBlacklistCreate) SetSessionHash(v string) *RiskSessionBlacklistCreate {
	_c.mutation.SetSessionHash(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RiskSessionBlacklistCreate) SetUserID(v int64) *RiskSessionBlacklistCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableUserID(v *int64) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *RiskSessionBlacklistCreate) SetAPIKeyID(v int64) *RiskSessionBlacklistCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableAPIKeyID(v *int64) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *RiskSessionBlacklistCreate) SetGroupID(v int64) *RiskSessionBlacklistCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableGroupID(v *int64) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *RiskSessionBlacklistCreate) SetReason(v string) *RiskSessionBlacklistCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableReason(v *string) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCategories sets the "categories" field.
func (_c *RiskSessionBlacklistCreate) SetCategories(v []string) *RiskSessionBlacklistCreate {
	_c.mutation.SetCategories(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *RiskSessionBlacklistCreate) SetConfidence(v float64) *RiskSessionBlacklistCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableConfidence(v *float64) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetAuditModel sets the "audit_model" field.
func (_c *RiskSessionBlacklistCreate) SetAuditModel(v string) *RiskSessionBlacklistCreate {
	_c.mutation.SetAuditModel(v)
	return _c
}

// SetNillableAuditModel sets the "audit_model" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableAuditModel(v *string) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetAuditModel(*v)
	}
	return _c
}

// SetAuditResponseID sets the "audit_response_id" field.
func (_c *RiskSessionBlacklistCreate) SetAuditResponseID(v string) *RiskSessionBlacklistCreate {
	_c.mutation.SetAuditResponseID(v)
	return _c
}

// SetNillableAuditResponseID sets the "audit_response_id" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableAuditResponseID(v *string) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetAuditResponseID(*v)
	}
	return _c
}

// SetSourceProtocol sets the "source_protocol" field.
func (_c *RiskSessionBlacklistCreate) SetSourceProtocol(v string) *RiskSessionBlacklistCreate {
	_c.mutation.SetSourceProtocol(v)
	return _c
}

// SetNillableSourceProtocol sets the "source_protocol" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableSourceProtocol(v *string) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetSourceProtocol(*v)
	}
	return _c
}

// SetSourceModel sets the "source_model" field.
func (_c *RiskSessionBlacklistCreate) SetSourceModel(v string) *RiskSessionBlacklistCreate {
	_c.mutation.SetSourceModel(v)
	return _c
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableSourceModel(v *string) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetSourceModel(*v)
	}
	return _c
}

// SetFirstBlockedAt sets the "first_blocked_at" field.
func (_c *RiskSessionBlacklistCreate) SetFirstBlockedAt(v time.Time) *RiskSessionBlacklistCreate {
	_c.mutation.SetFirstBlockedAt(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *RiskSessionBlacklistCreate) SetLastSeenAt(v time.Time) *RiskSessionBlacklistCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RiskSessionBlacklistCreate) SetExpiresAt(v time.Time) *RiskSessionBlacklistCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *RiskSessionBlacklistCreate) SetNillableExpiresAt(v *time.Time) *RiskSessionBlacklistCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the RiskSessionBlacklistMutation object of the builder.
func (_c *RiskSessionBlacklistCreate) Mutation() *RiskSessionBlacklistMutation {
	return _c.mutation
}

// Save creates the RiskSessionBlacklist in the database.
func (_c *RiskSessionBlacklistCreate) Save(ctx context.Context) (*RiskSessionBlacklist, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RiskSessionBlacklistCreate) SaveX(ctx context.Context) *RiskSessionBlacklist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RiskSessionBlacklistCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RiskSessionBlacklistCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RiskSessionBlacklistCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := risksessionblacklist.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := risksessionblacklist.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := risksessionblacklist.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := risksessionblacklist.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.AuditModel(); !ok {
		v := risksessionblacklist.DefaultAuditModel
		_c.mutation.SetAuditModel(v)
	}
	if _, ok := _c.mutation.AuditResponseID(); !ok {
		v := risksessionblacklist.DefaultAuditResponseID
		_c.mutation.SetAuditResponseID(v)
	}
	if _, ok := _c.mutation.SourceProtocol(); !ok {
		v := risksessionblacklist.DefaultSourceProtocol
		_c.mutation.SetSourceProtocol(v)
	}
	if _, ok := _c.mutation.SourceModel(); !ok {
		v := risksessionblacklist.DefaultSourceModel
		_c.mutation.SetSourceModel(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RiskSessionBlacklistCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RiskSessionBlacklist.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RiskSessionBlacklist.updated_at"`)}
	}
	if _, ok := _c.mutation.SessionHash(); !ok {
		return &ValidationError{Name: "session_hash", err: errors.New(`ent: missing required field "RiskSessionBlacklist.session_hash"`)}
	}
	if v, ok := _c.mutation.SessionHash(); ok {
		if err := risksessionblacklist.SessionHashValidator(v); err != nil {
			return &ValidationError{Name: "session_hash", err: fmt.Errorf(`ent: validator failed for field "RiskSessionBlacklist.session_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "RiskSessionBlacklist.reason"`)}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "RiskSessionBlacklist.confidence"`)}
	}
	if _, ok := _c.mutation.AuditModel(); !ok {
		return &ValidationError{Name: "audit_model", err: errors.New(`ent: missing required field "RiskSessionBlacklist.audit_model"`)}
	}
	if _, ok := _c.mutation.AuditResponseID(); !ok {
		return &ValidationError{Name: "audit_response_id", err: errors.New(`ent: missing required field "RiskSessionBlacklist.audit_response_id"`)}
	}
	if _, ok := _c.mutation.SourceProtocol(); !ok {
		return &ValidationError{Name: "source_protocol", err: errors.New(`ent: missing required field "RiskSessionBlacklist.source_protocol"`)}
	}
	if _, ok := _c.mutation.SourceModel(); !ok {
		return &ValidationError{Name: "source_model", err: errors.New(`ent: missing required field "RiskSessionBlacklist.source_model"`)}
	}
	if _, ok := _c.mutation.FirstBlockedAt(); !ok {
		return &ValidationError{Name: "first_blocked_at", err: errors.New(`ent: missing required field "RiskSessionBlacklist.first_blocked_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "RiskSessionBlacklist.last_seen_at"`)}
	}
	return nil
}

func (_c *RiskSessionBlacklistCreate) sqlSave(ctx context.Context) (*RiskSessionBlacklist, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RiskSessionBlacklistCreate) createSpec() (*RiskSessionBlacklist, *sqlgraph.CreateSpec) {
	var (
		_node = &RiskSessionBlacklist{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(risksessionblacklist.Table, sqlgraph.NewFieldSpec(risksessionblacklist.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SessionHash(); ok {
		_spec.SetField(risksessionblacklist.FieldSessionHash, field.TypeString, value)
		_node.SessionHash = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(risksessionblacklist.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(risksessionblacklist.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(risksessionblacklist.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Categories(); ok {
		_spec.SetField(risksessionblacklist.FieldCategories, field.TypeJSON, value)
		_node.Categories = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(risksessionblacklist.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.AuditModel(); ok {
		_spec.SetField(risksessionblacklist.FieldAuditModel, field.TypeString, value)
		_node.AuditModel = value
	}
	if value, ok := _c.mutation.AuditResponseID(); ok {
		_spec.SetField(risksessionblacklist.FieldAuditResponseID, field.TypeString, value)
		_node.AuditResponseID = value
	}
	if value, ok := _c.mutation.SourceProtocol(); ok {
		_spec.SetField(risksessionblacklist.FieldSourceProtocol, field.TypeString, value)
		_node.SourceProtocol = value
	}
	if value, ok := _c.mutation.SourceModel(); ok {
		_spec.SetField(risksessionblacklist.FieldSourceModel, field.TypeString, value)
		_node.SourceModel = value
	}
	if value, ok := _c.mutation.FirstBlockedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldFirstBlockedAt, field.TypeTime, value)
		_node.FirstBlockedAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(risksessionblacklist.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(risksessionblacklist.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RiskSessionBlacklist.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RiskSessionBlacklistUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RiskSessionBlacklistCreate) OnConflict(opts ...sql.ConflictOption) *RiskSessionBlacklistUpsertOne {
	_c.conflict = opts
	return &RiskSessionBlacklistUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RiskSessionBlacklist.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RiskSessionBlacklistCreate) OnConflictColumns(columns ...string) *RiskSessionBlacklistUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RiskSessionBlacklistUpsertOne{
		create: _c,
	}
}

type (
	// RiskSessionBlacklistUpsertOne is the builder for "upsert"-ing
	//  one RiskSessionBlacklist node.
	RiskSessionBlacklistUpsertOne struct {
		create *RiskSessionBlacklistCreate
	}

	// RiskSessionBlacklistUpsert is the "OnConflict" setter.
	RiskSessionBlacklistUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RiskSessionBlacklistUpsert) SetUpdatedAt(v time.Time) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateUpdatedAt() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldUpdatedAt)
	return u
}

// SetSessionHash sets the "session_hash" field.
func (u *RiskSessionBlacklistUpsert) SetSessionHash(v string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldSessionHash, v)
	return u
}

// UpdateSessionHash sets the "session_hash" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateSessionHash() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldSessionHash)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RiskSessionBlacklistUpsert) SetUserID(v int64) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateUserID() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *RiskSessionBlacklistUpsert) AddUserID(v int64) *RiskSessionBlacklistUpsert {
	u.Add(risksessionblacklist.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *RiskSessionBlacklistUpsert) ClearUserID() *RiskSessionBlacklistUpsert {
	u.SetNull(risksessionblacklist.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RiskSessionBlacklistUpsert) SetAPIKeyID(v int64) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateAPIKeyID() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RiskSessionBlacklistUpsert) AddAPIKeyID(v int64) *RiskSessionBlacklistUpsert {
	u.Add(risksessionblacklist.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *RiskSessionBlacklistUpsert) ClearAPIKeyID() *RiskSessionBlacklistUpsert {
	u.SetNull(risksessionblacklist.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *RiskSessionBlacklistUpsert) SetGroupID(v int64) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateGroupID() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *RiskSessionBlacklistUpsert) AddGroupID(v int64) *RiskSessionBlacklistUpsert {
	u.Add(risksessionblacklist.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RiskSessionBlacklistUpsert) ClearGroupID() *RiskSessionBlacklistUpsert {
	u.SetNull(risksessionblacklist.FieldGroupID)
	return u
}

// SetReason sets the "reason" field.
func (u *RiskSessionBlacklistUpsert) SetReason(v string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateReason() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldReason)
	return u
}

// SetCategories sets the "categories" field.
func (u *RiskSessionBlacklistUpsert) SetCategories(v []string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldCategories, v)
	return u
}

// UpdateCategories sets the "categories" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateCategories() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldCategories)
	return u
}

// ClearCategories clears the value of the "categories" field.
func (u *RiskSessionBlacklistUpsert) ClearCategories() *RiskSessionBlacklistUpsert {
	u.SetNull(risksessionblacklist.FieldCategories)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *RiskSessionBlacklistUpsert) SetConfidence(v float64) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateConfidence() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldConfidence)
	return u
}

// AddConfidence adds v to the "confidence" field.
func (u *RiskSessionBlacklistUpsert) AddConfidence(v float64) *RiskSessionBlacklistUpsert {
	u.Add(risksessionblacklist.FieldConfidence, v)
	return u
}

// SetAuditModel sets the "audit_model" field.
func (u *RiskSessionBlacklistUpsert) SetAuditModel(v string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldAuditModel, v)
	return u
}

// UpdateAuditModel sets the "audit_model" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateAuditModel() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldAuditModel)
	return u
}

// SetAuditResponseID sets the "audit_response_id" field.
func (u *RiskSessionBlacklistUpsert) SetAuditResponseID(v string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldAuditResponseID, v)
	return u
}

// UpdateAuditResponseID sets the "audit_response_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateAuditResponseID() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldAuditResponseID)
	return u
}

// SetSourceProtocol sets the "source_protocol" field.
func (u *RiskSessionBlacklistUpsert) SetSourceProtocol(v string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldSourceProtocol, v)
	return u
}

// UpdateSourceProtocol sets the "source_protocol" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateSourceProtocol() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldSourceProtocol)
	return u
}

// SetSourceModel sets the "source_model" field.
func (u *RiskSessionBlacklistUpsert) SetSourceModel(v string) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldSourceModel, v)
	return u
}

// UpdateSourceModel sets the "source_model" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateSourceModel() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldSourceModel)
	return u
}

// SetFirstBlockedAt sets the "first_blocked_at" field.
func (u *RiskSessionBlacklistUpsert) SetFirstBlockedAt(v time.Time) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldFirstBlockedAt, v)
	return u
}

// UpdateFirstBlockedAt sets the "first_blocked_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateFirstBlockedAt() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldFirstBlockedAt)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *RiskSessionBlacklistUpsert) SetLastSeenAt(v time.Time) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateLastSeenAt() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldLastSeenAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *RiskSessionBlacklistUpsert) SetExpiresAt(v time.Time) *RiskSessionBlacklistUpsert {
	u.Set(risksessionblacklist.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsert) UpdateExpiresAt() *RiskSessionBlacklistUpsert {
	u.SetExcluded(risksessionblacklist.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RiskSessionBlacklistUpsert) ClearExpiresAt() *RiskSessionBlacklistUpsert {
	u.SetNull(risksessionblacklist.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RiskSessionBlacklist.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RiskSessionBlacklistUpsertOne) UpdateNewValues() *RiskSessionBlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(risksessionblacklist.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RiskSessionBlacklist.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RiskSessionBlacklistUpsertOne) Ignore() *RiskSessionBlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RiskSessionBlacklistUpsertOne) DoNothing() *RiskSessionBlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RiskSessionBlacklistCreate.OnConflict
// documentation for more info.
func (u *RiskSessionBlacklistUpsertOne) Update(set func(*RiskSessionBlacklistUpsert)) *RiskSessionBlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RiskSessionBlacklistUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RiskSessionBlacklistUpsertOne) SetUpdatedAt(v time.Time) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateUpdatedAt() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSessionHash sets the "session_hash" field.
func (u *RiskSessionBlacklistUpsertOne) SetSessionHash(v string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetSessionHash(v)
	})
}

// UpdateSessionHash sets the "session_hash" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateSessionHash() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateSessionHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *RiskSessionBlacklistUpsertOne) SetUserID(v int64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RiskSessionBlacklistUpsertOne) AddUserID(v int64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateUserID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *RiskSessionBlacklistUpsertOne) ClearUserID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RiskSessionBlacklistUpsertOne) SetAPIKeyID(v int64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RiskSessionBlacklistUpsertOne) AddAPIKeyID(v int64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateAPIKeyID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *RiskSessionBlacklistUpsertOne) ClearAPIKeyID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RiskSessionBlacklistUpsertOne) SetGroupID(v int64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RiskSessionBlacklistUpsertOne) AddGroupID(v int64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateGroupID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RiskSessionBlacklistUpsertOne) ClearGroupID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearGroupID()
	})
}

// SetReason sets the "reason" field.
func (u *RiskSessionBlacklistUpsertOne) SetReason(v string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateReason() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateReason()
	})
}

// SetCategories sets the "categories" field.
func (u *RiskSessionBlacklistUpsertOne) SetCategories(v []string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetCategories(v)
	})
}

// UpdateCategories sets the "categories" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateCategories() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateCategories()
	})
}

// ClearCategories clears the value of the "categories" field.
func (u *RiskSessionBlacklistUpsertOne) ClearCategories() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearCategories()
	})
}

// SetConfidence sets the "confidence" field.
func (u *RiskSessionBlacklistUpsertOne) SetConfidence(v float64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *RiskSessionBlacklistUpsertOne) AddConfidence(v float64) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateConfidence() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateConfidence()
	})
}

// SetAuditModel sets the "audit_model" field.
func (u *RiskSessionBlacklistUpsertOne) SetAuditModel(v string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetAuditModel(v)
	})
}

// UpdateAuditModel sets the "audit_model" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateAuditModel() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateAuditModel()
	})
}

// SetAuditResponseID sets the "audit_response_id" field.
func (u *RiskSessionBlacklistUpsertOne) SetAuditResponseID(v string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetAuditResponseID(v)
	})
}

// UpdateAuditResponseID sets the "audit_response_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateAuditResponseID() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateAuditResponseID()
	})
}

// SetSourceProtocol sets the "source_protocol" field.
func (u *RiskSessionBlacklistUpsertOne) SetSourceProtocol(v string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetSourceProtocol(v)
	})
}

// UpdateSourceProtocol sets the "source_protocol" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateSourceProtocol() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateSourceProtocol()
	})
}

// SetSourceModel sets the "source_model" field.
func (u *RiskSessionBlacklistUpsertOne) SetSourceModel(v string) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetSourceModel(v)
	})
}

// UpdateSourceModel sets the "source_model" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateSourceModel() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateSourceModel()
	})
}

// SetFirstBlockedAt sets the "first_blocked_at" field.
func (u *RiskSessionBlacklistUpsertOne) SetFirstBlockedAt(v time.Time) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetFirstBlockedAt(v)
	})
}

// UpdateFirstBlockedAt sets the "first_blocked_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateFirstBlockedAt() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateFirstBlockedAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *RiskSessionBlacklistUpsertOne) SetLastSeenAt(v time.Time) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateLastSeenAt() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RiskSessionBlacklistUpsertOne) SetExpiresAt(v time.Time) *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertOne) UpdateExpiresAt() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RiskSessionBlacklistUpsertOne) ClearExpiresAt() *RiskSessionBlacklistUpsertOne {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *RiskSessionBlacklistUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RiskSessionBlacklistCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RiskSessionBlacklistUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RiskSessionBlacklistUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RiskSessionBlacklistUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RiskSessionBlacklistCreateBulk is the builder for creating many RiskSessionBlacklist entities in bulk.
type RiskSessionBlacklistCreateBulk struct {
	config
	err      error
	builders []*RiskSessionBlacklistCreate
	conflict []sql.ConflictOption
}

// Save creates the RiskSessionBlacklist entities in the database.
func (_c *RiskSessionBlacklistCreateBulk) Save(ctx context.Context) ([]*RiskSessionBlacklist, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RiskSessionBlacklist, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RiskSessionBlacklistMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RiskSessionBlacklistCreateBulk) SaveX(ctx context.Context) []*RiskSessionBlacklist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RiskSessionBlacklistCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RiskSessionBlacklistCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RiskSessionBlacklist.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RiskSessionBlacklistUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RiskSessionBlacklistCreateBulk) OnConflict(opts ...sql.ConflictOption) *RiskSessionBlacklistUpsertBulk {
	_c.conflict = opts
	return &RiskSessionBlacklistUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RiskSessionBlacklist.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RiskSessionBlacklistCreateBulk) OnConflictColumns(columns ...string) *RiskSessionBlacklistUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RiskSessionBlacklistUpsertBulk{
		create: _c,
	}
}

// RiskSessionBlacklistUpsertBulk is the builder for "upsert"-ing
// a bulk of RiskSessionBlacklist nodes.
type RiskSessionBlacklistUpsertBulk struct {
	create *RiskSessionBlacklistCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RiskSessionBlacklist.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RiskSessionBlacklistUpsertBulk) UpdateNewValues() *RiskSessionBlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(risksessionblacklist.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RiskSessionBlacklist.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RiskSessionBlacklistUpsertBulk) Ignore() *RiskSessionBlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RiskSessionBlacklistUpsertBulk) DoNothing() *RiskSessionBlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RiskSessionBlacklistCreateBulk.OnConflict
// documentation for more info.
func (u *RiskSessionBlacklistUpsertBulk) Update(set func(*RiskSessionBlacklistUpsert)) *RiskSessionBlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RiskSessionBlacklistUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RiskSessionBlacklistUpsertBulk) SetUpdatedAt(v time.Time) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateUpdatedAt() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSessionHash sets the "session_hash" field.
func (u *RiskSessionBlacklistUpsertBulk) SetSessionHash(v string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetSessionHash(v)
	})
}

// UpdateSessionHash sets the "session_hash" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateSessionHash() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateSessionHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *RiskSessionBlacklistUpsertBulk) SetUserID(v int64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RiskSessionBlacklistUpsertBulk) AddUserID(v int64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateUserID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *RiskSessionBlacklistUpsertBulk) ClearUserID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RiskSessionBlacklistUpsertBulk) SetAPIKeyID(v int64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RiskSessionBlacklistUpsertBulk) AddAPIKeyID(v int64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateAPIKeyID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *RiskSessionBlacklistUpsertBulk) ClearAPIKeyID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RiskSessionBlacklistUpsertBulk) SetGroupID(v int64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RiskSessionBlacklistUpsertBulk) AddGroupID(v int64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateGroupID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RiskSessionBlacklistUpsertBulk) ClearGroupID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearGroupID()
	})
}

// SetReason sets the "reason" field.
func (u *RiskSessionBlacklistUpsertBulk) SetReason(v string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateReason() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateReason()
	})
}

// SetCategories sets the "categories" field.
func (u *RiskSessionBlacklistUpsertBulk) SetCategories(v []string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetCategories(v)
	})
}

// UpdateCategories sets the "categories" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateCategories() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateCategories()
	})
}

// ClearCategories clears the value of the "categories" field.
func (u *RiskSessionBlacklistUpsertBulk) ClearCategories() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearCategories()
	})
}

// SetConfidence sets the "confidence" field.
func (u *RiskSessionBlacklistUpsertBulk) SetConfidence(v float64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *RiskSessionBlacklistUpsertBulk) AddConfidence(v float64) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateConfidence() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateConfidence()
	})
}

// SetAuditModel sets the "audit_model" field.
func (u *RiskSessionBlacklistUpsertBulk) SetAuditModel(v string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetAuditModel(v)
	})
}

// UpdateAuditModel sets the "audit_model" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateAuditModel() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateAuditModel()
	})
}

// SetAuditResponseID sets the "audit_response_id" field.
func (u *RiskSessionBlacklistUpsertBulk) SetAuditResponseID(v string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetAuditResponseID(v)
	})
}

// UpdateAuditResponseID sets the "audit_response_id" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateAuditResponseID() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateAuditResponseID()
	})
}

// SetSourceProtocol sets the "source_protocol" field.
func (u *RiskSessionBlacklistUpsertBulk) SetSourceProtocol(v string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetSourceProtocol(v)
	})
}

// UpdateSourceProtocol sets the "source_protocol" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateSourceProtocol() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateSourceProtocol()
	})
}

// SetSourceModel sets the "source_model" field.
func (u *RiskSessionBlacklistUpsertBulk) SetSourceModel(v string) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetSourceModel(v)
	})
}

// UpdateSourceModel sets the "source_model" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateSourceModel() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateSourceModel()
	})
}

// SetFirstBlockedAt sets the "first_blocked_at" field.
func (u *RiskSessionBlacklistUpsertBulk) SetFirstBlockedAt(v time.Time) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetFirstBlockedAt(v)
	})
}

// UpdateFirstBlockedAt sets the "first_blocked_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateFirstBlockedAt() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateFirstBlockedAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *RiskSessionBlacklistUpsertBulk) SetLastSeenAt(v time.Time) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateLastSeenAt() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RiskSessionBlacklistUpsertBulk) SetExpiresAt(v time.Time) *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RiskSessionBlacklistUpsertBulk) UpdateExpiresAt() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RiskSessionBlacklistUpsertBulk) ClearExpiresAt() *RiskSessionBlacklistUpsertBulk {
	return u.Update(func(s *RiskSessionBlacklistUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *RiskSessionBlacklistUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RiskSessionBlacklistCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RiskSessionBlacklistCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RiskSessionBlacklistUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
