// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/risksessionblacklist"
)

// RiskSessionBlacklistUpdate is the builder for updating RiskSessionBlacklist entities.
type RiskSessionBlacklistUpdate struct {
	config
	hooks    []Hook
	mutation *RiskSessionBlacklistMutation
}

// Where appends a list predicates to the RiskSessionBlacklistUpdate builder.
func (_u *RiskSessionBlacklistUpdate) Where(ps ...predicate.RiskSessionBlacklist) *RiskSessionBlacklistUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RiskSessionBlacklistUpdate) SetUpdatedAt(v time.Time) *RiskSessionBlacklistUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionHash sets the "session_hash" field.
func (_u *RiskSessionBlacklistUpdate) SetSessionHash(v string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetSessionHash(v)
	return _u
}

// SetNillableSessionHash sets the "session_hash" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableSessionHash(v *string) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetSessionHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RiskSessionBlacklistUpdate) SetUserID(v int64) *RiskSessionBlacklistUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableUserID(v *int64) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RiskSessionBlacklistUpdate) AddUserID(v int64) *RiskSessionBlacklistUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *RiskSessionBlacklistUpdate) ClearUserID() *RiskSessionBlacklistUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RiskSessionBlacklistUpdate) SetAPIKeyID(v int64) *RiskSessionBlacklistUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableAPIKeyID(v *int64) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *RiskSessionBlacklistUpdate) AddAPIKeyID(v int64) *RiskSessionBlacklistUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *RiskSessionBlacklistUpdate) ClearAPIKeyID() *RiskSessionBlacklistUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RiskSessionBlacklistUpdate) SetGroupID(v int64) *RiskSessionBlacklistUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableGroupID(v *int64) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RiskSessionBlacklistUpdate) AddGroupID(v int64) *RiskSessionBlacklistUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RiskSessionBlacklistUpdate) ClearGroupID() *RiskSessionBlacklistUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *RiskSessionBlacklistUpdate) SetReason(v string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableReason(v *string) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetCategories sets the "categories" field.
func (_u *RiskSessionBlacklistUpdate) SetCategories(v []string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetCategories(v)
	return _u
}

// AppendCategories appends value to the "categories" field.
func (_u *RiskSessionBlacklistUpdate) AppendCategories(v []string) *RiskSessionBlacklistUpdate {
	_u.mutation.AppendCategories(v)
	return _u
}

// ClearCategories clears the value of the "categories" field.
func (_u *RiskSessionBlacklistUpdate) ClearCategories() *RiskSessionBlacklistUpdate {
	_u.mutation.ClearCategories()
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *RiskSessionBlacklistUpdate) SetConfidence(v float64) *RiskSessionBlacklistUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableConfidence(v *float64) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *RiskSessionBlacklistUpdate) AddConfidence(v float64) *RiskSessionBlacklistUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetAuditModel sets the "audit_model" field.
func (_u *RiskSessionBlacklistUpdate) SetAuditModel(v string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetAuditModel(v)
	return _u
}

// SetNillableAuditModel sets the "audit_model" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableAuditModel(v *string) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetAuditModel(*v)
	}
	return _u
}

// SetAuditResponseID sets the "audit_response_id" field.
func (_u *RiskSessionBlacklistUpdate) SetAuditResponseID(v string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetAuditResponseID(v)
	return _u
}

// SetNillableAuditResponseID sets the "audit_response_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableAuditResponseID(v *string) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetAuditResponseID(*v)
	}
	return _u
}

// SetSourceProtocol sets the "source_protocol" field.
func (_u *RiskSessionBlacklistUpdate) SetSourceProtocol(v string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetSourceProtocol(v)
	return _u
}

// SetNillableSourceProtocol sets the "source_protocol" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableSourceProtocol(v *string) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetSourceProtocol(*v)
	}
	return _u
}

// SetSourceModel sets the "source_model" field.
func (_u *RiskSessionBlacklistUpdate) SetSourceModel(v string) *RiskSessionBlacklistUpdate {
	_u.mutation.SetSourceModel(v)
	return _u
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableSourceModel(v *string) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetSourceModel(*v)
	}
	return _u
}

// SetFirstBlockedAt sets the "first_blocked_at" field.
func (_u *RiskSessionBlacklistUpdate) SetFirstBlockedAt(v time.Time) *RiskSessionBlacklistUpdate {
	_u.mutation.SetFirstBlockedAt(v)
	return _u
}

// SetNillableFirstBlockedAt sets the "first_blocked_at" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableFirstBlockedAt(v *time.Time) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetFirstBlockedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *RiskSessionBlacklistUpdate) SetLastSeenAt(v time.Time) *RiskSessionBlacklistUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableLastSeenAt(v *time.Time) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RiskSessionBlacklistUpdate) SetExpiresAt(v time.Time) *RiskSessionBlacklistUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdate) SetNillableExpiresAt(v *time.Time) *RiskSessionBlacklistUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RiskSessionBlacklistUpdate) ClearExpiresAt() *RiskSessionBlacklistUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the RiskSessionBlacklistMutation object of the builder.
func (_u *RiskSessionBlacklistUpdate) Mutation() *RiskSessionBlacklistMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RiskSessionBlacklistUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RiskSessionBlacklistUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RiskSessionBlacklistUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RiskSessionBlacklistUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RiskSessionBlacklistUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := risksessionblacklist.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RiskSessionBlacklistUpdate) check() error {
	if v, ok := _u.mutation.SessionHash(); ok {
		if err := risksessionblacklist.SessionHashValidator(v); err != nil {
			return &ValidationError{Name: "session_hash", err: fmt.Errorf(`ent: validator failed for field "RiskSessionBlacklist.session_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *RiskSessionBlacklistUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(risksessionblacklist.Table, risksessionblacklist.Columns, sqlgraph.NewFieldSpec(risksessionblacklist.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionHash(); ok {
		_spec.SetField(risksessionblacklist.FieldSessionHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(risksessionblacklist.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(risksessionblacklist.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(risksessionblacklist.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(risksessionblacklist.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(risksessionblacklist.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(risksessionblacklist.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(risksessionblacklist.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Categories(); ok {
		_spec.SetField(risksessionblacklist.FieldCategories, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCategories(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, risksessionblacklist.FieldCategories, value)
		})
	}
	if _u.mutation.CategoriesCleared() {
		_spec.ClearField(risksessionblacklist.FieldCategories, field.TypeJSON)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(risksessionblacklist.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(risksessionblacklist.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AuditModel(); ok {
		_spec.SetField(risksessionblacklist.FieldAuditModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuditResponseID(); ok {
		_spec.SetField(risksessionblacklist.FieldAuditResponseID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceProtocol(); ok {
		_spec.SetField(risksessionblacklist.FieldSourceProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceModel(); ok {
		_spec.SetField(risksessionblacklist.FieldSourceModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstBlockedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldFirstBlockedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(risksessionblacklist.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(risksessionblacklist.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(risksessionblacklist.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{risksessionblacklist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RiskSessionBlacklistUpdateOne is the builder for updating a single RiskSessionBlacklist entity.
type RiskSessionBlacklistUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RiskSessionBlacklistMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RiskSessionBlacklistUpdateOne) SetUpdatedAt(v time.Time) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionHash sets the "session_hash" field.
func (_u *RiskSessionBlacklistUpdateOne) SetSessionHash(v string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetSessionHash(v)
	return _u
}

// SetNillableSessionHash sets the "session_hash" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableSessionHash(v *string) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetSessionHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RiskSessionBlacklistUpdateOne) SetUserID(v int64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableUserID(v *int64) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RiskSessionBlacklistUpdateOne) AddUserID(v int64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *RiskSessionBlacklistUpdateOne) ClearUserID() *RiskSessionBlacklistUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RiskSessionBlacklistUpdateOne) SetAPIKeyID(v int64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableAPIKeyID(v *int64) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *RiskSessionBlacklistUpdateOne) AddAPIKeyID(v int64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *RiskSessionBlacklistUpdateOne) ClearAPIKeyID() *RiskSessionBlacklistUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RiskSessionBlacklistUpdateOne) SetGroupID(v int64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableGroupID(v *int64) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RiskSessionBlacklistUpdateOne) AddGroupID(v int64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RiskSessionBlacklistUpdateOne) ClearGroupID() *RiskSessionBlacklistUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *RiskSessionBlacklistUpdateOne) SetReason(v string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableReason(v *string) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetCategories sets the "categories" field.
func (_u *RiskSessionBlacklistUpdateOne) SetCategories(v []string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetCategories(v)
	return _u
}

// AppendCategories appends value to the "categories" field.
func (_u *RiskSessionBlacklistUpdateOne) AppendCategories(v []string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.AppendCategories(v)
	return _u
}

// ClearCategories clears the value of the "categories" field.
func (_u *RiskSessionBlacklistUpdateOne) ClearCategories() *RiskSessionBlacklistUpdateOne {
	_u.mutation.ClearCategories()
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *RiskSessionBlacklistUpdateOne) SetConfidence(v float64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableConfidence(v *float64) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *RiskSessionBlacklistUpdateOne) AddConfidence(v float64) *RiskSessionBlacklistUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetAuditModel sets the "audit_model" field.
func (_u *RiskSessionBlacklistUpdateOne) SetAuditModel(v string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetAuditModel(v)
	return _u
}

// SetNillableAuditModel sets the "audit_model" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableAuditModel(v *string) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetAuditModel(*v)
	}
	return _u
}

// SetAuditResponseID sets the "audit_response_id" field.
func (_u *RiskSessionBlacklistUpdateOne) SetAuditResponseID(v string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetAuditResponseID(v)
	return _u
}

// SetNillableAuditResponseID sets the "audit_response_id" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableAuditResponseID(v *string) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetAuditResponseID(*v)
	}
	return _u
}

// SetSourceProtocol sets the "source_protocol" field.
func (_u *RiskSessionBlacklistUpdateOne) SetSourceProtocol(v string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetSourceProtocol(v)
	return _u
}

// SetNillableSourceProtocol sets the "source_protocol" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableSourceProtocol(v *string) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetSourceProtocol(*v)
	}
	return _u
}

// SetSourceModel sets the "source_model" field.
func (_u *RiskSessionBlacklistUpdateOne) SetSourceModel(v string) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetSourceModel(v)
	return _u
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableSourceModel(v *string) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetSourceModel(*v)
	}
	return _u
}

// SetFirstBlockedAt sets the "first_blocked_at" field.
func (_u *RiskSessionBlacklistUpdateOne) SetFirstBlockedAt(v time.Time) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetFirstBlockedAt(v)
	return _u
}

// SetNillableFirstBlockedAt sets the "first_blocked_at" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableFirstBlockedAt(v *time.Time) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetFirstBlockedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *RiskSessionBlacklistUpdateOne) SetLastSeenAt(v time.Time) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableLastSeenAt(v *time.Time) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RiskSessionBlacklistUpdateOne) SetExpiresAt(v time.Time) *RiskSessionBlacklistUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RiskSessionBlacklistUpdateOne) SetNillableExpiresAt(v *time.Time) *RiskSessionBlacklistUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RiskSessionBlacklistUpdateOne) ClearExpiresAt() *RiskSessionBlacklistUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the RiskSessionBlacklistMutation object of the builder.
func (_u *RiskSessionBlacklistUpdateOne) Mutation() *RiskSessionBlacklistMutation {
	return _u.mutation
}

// Where appends a list predicates to the RiskSessionBlacklistUpdate builder.
func (_u *RiskSessionBlacklistUpdateOne) Where(ps ...predicate.RiskSessionBlacklist) *RiskSessionBlacklistUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RiskSessionBlacklistUpdateOne) Select(field string, fields ...string) *RiskSessionBlacklistUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RiskSessionBlacklist entity.
func (_u *RiskSessionBlacklistUpdateOne) Save(ctx context.Context) (*RiskSessionBlacklist, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RiskSessionBlacklistUpdateOne) SaveX(ctx context.Context) *RiskSessionBlacklist {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RiskSessionBlacklistUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RiskSessionBlacklistUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RiskSessionBlacklistUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := risksessionblacklist.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RiskSessionBlacklistUpdateOne) check() error {
	if v, ok := _u.mutation.SessionHash(); ok {
		if err := risksessionblacklist.SessionHashValidator(v); err != nil {
			return &ValidationError{Name: "session_hash", err: fmt.Errorf(`ent: validator failed for field "RiskSessionBlacklist.session_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *RiskSessionBlacklistUpdateOne) sqlSave(ctx context.Context) (_node *RiskSessionBlacklist, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(risksessionblacklist.Table, risksessionblacklist.Columns, sqlgraph.NewFieldSpec(risksessionblacklist.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RiskSessionBlacklist.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, risksessionblacklist.FieldID)
		for _, f := range fields {
			if !risksessionblacklist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != risksessionblacklist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionHash(); ok {
		_spec.SetField(risksessionblacklist.FieldSessionHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(risksessionblacklist.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(risksessionblacklist.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(risksessionblacklist.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(risksessionblacklist.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(risksessionblacklist.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(risksessionblacklist.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(risksessionblacklist.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(risksessionblacklist.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Categories(); ok {
		_spec.SetField(risksessionblacklist.FieldCategories, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCategories(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, risksessionblacklist.FieldCategories, value)
		})
	}
	if _u.mutation.CategoriesCleared() {
		_spec.ClearField(risksessionblacklist.FieldCategories, field.TypeJSON)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(risksessionblacklist.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(risksessionblacklist.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AuditModel(); ok {
		_spec.SetField(risksessionblacklist.FieldAuditModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuditResponseID(); ok {
		_spec.SetField(risksessionblacklist.FieldAuditResponseID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceProtocol(); ok {
		_spec.SetField(risksessionblacklist.FieldSourceProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceModel(); ok {
		_spec.SetField(risksessionblacklist.FieldSourceModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstBlockedAt(); ok {
		_spec.SetField(risksessionblacklist.FieldFirstBlockedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(risksessionblacklist.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(risksessionblacklist.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(risksessionblacklist.FieldExpiresAt, field.TypeTime)
	}
	_node = &RiskSessionBlacklist{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{risksessionblacklist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
